### ISSUE TITLE
Separate fixtures from actual tests

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/client-integration-tests#11]
We could have something like this:

http://httpbin.org/

At the beginning we would have to start a webserver, then use it in the tests.

**Comment by joelwurtz** [comment]
Cannot we just use the website by default and add the binary optional when it is need in offline environment ?

**Comment by sagikazarmark** [comment]
I would rather not rely on an external service.

**Comment by joelwurtz** [comment]
Yes bad idea :)
Le 2 nov. 2015 1:42 PM, "Márk Sági-Kazár" <notifications@github.com> a
écrit :
