### ISSUE TITLE
Tests for TRACE requests should not send/expect body

### ISSUE THREAD

**Issue by mekras** [php-http/client-integration-tests#18]
| Q | A |
| --- | --- |
| Bug? | probably |
| New Feature? | no |
| Version | 0.5.1 |

According to [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.8):

> A client MUST NOT send a message body in a TRACE request.

But some data sets provided by [HttpBaseTest::requestProvider](https://github.com/php-http/client-integration-tests/blob/v0.5.1/src/HttpBaseTest.php#L64) contain body for TRACE requests.

**Comment by kelunik** [comment]
Didn't see this issue before, solved via #29.
