### ISSUE TITLE
Add class alias for compatibility with older PHPUnit versions

### ISSUE THREAD

**Issue by Nyholm** [php-http/client-integration-tests#23]
See discussions here: https://github.com/php-http/client-integration-tests/pull/21#discussion_r106778781

**Comment by joelwurtz** [comment]
Is it still needed ? No one complaint about that so i believe we are good not doing it :D. Also last PR force version of PHPUnit to the 7.x one

**Comment by Nyholm** [comment]
Na. Let’s close
