### ISSUE TITLE
Bug in HttpClientTest::testSendWithInvalidUri

### ISSUE THREAD

**Issue by fenric** [php-http/client-integration-tests#41]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | ffd1d52fb89d693ecc0e42a6973eaa153d1fee32

Your code:

https://github.com/php-http/client-integration-tests/blob/ffd1d52fb89d693ecc0e42a6973eaa153d1fee32/src/HttpClientTest.php#L97-L110

Maybe it will be right like this:

```php
/**
 * @expectedException \Psr\Http\Client\NetworkExceptionInterface
 * @group integration
 */
```

https://www.php-fig.org/psr/psr-18/#networkexceptioninterface

**Comment by Nyholm** [comment]
That is correct. Could you send a PR?

**Comment by joelwurtz** [comment]
I have done the PR in #42 @Nyholm
